# Generated by Django 6.0 on 2025-12-23 04:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closes_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_votes', models.IntegerField(default=0)),
                ('trigger', models.CharField(choices=[('FOUNDING', 'Founding Election'), ('RESIGNATION', 'Leader Resignation'), ('NO_CONFIDENCE', 'Vote of No Confidence'), ('SCHEDULED', 'Scheduled Election'), ('VACANCY', 'Leadership Vacancy')], default='SCHEDULED', max_length=20)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_leadership_elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField(blank=True, help_text='Campaign platform')),
                ('nominated_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('nominated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership_nominations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_candidacies', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='parties.leadershipelection')),
            ],
            options={
                'ordering': ['-nominated_at'],
                'unique_together': {('election', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(default='#808080', help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('logo', models.TextField(blank=True, help_text='Base64 encoded logo image')),
                ('ideology', models.CharField(choices=[('LEFT', 'Left Wing'), ('CENTER_LEFT', 'Center-Left'), ('CENTER', 'Centrist'), ('CENTER_RIGHT', 'Center-Right'), ('RIGHT', 'Right Wing'), ('OTHER', 'Other')], default='CENTER', max_length=20)),
                ('platform', models.TextField(blank=True, help_text='Party platform and policies')),
                ('founded_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_count', models.IntegerField(default=0)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_party', to=settings.AUTH_USER_MODEL)),
                ('press_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_secretary_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['-member_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='leadershipelection',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_elections', to='parties.party'),
        ),
        migrations.CreateModel(
            name='ConfidenceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Vote of No Confidence', max_length=200)),
                ('reason', models.TextField(help_text='Reason for calling this vote')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closes_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('votes_no_confidence', models.IntegerField(default=0)),
                ('votes_confidence', models.IntegerField(default=0)),
                ('result', models.CharField(blank=True, max_length=20)),
                ('threshold_percentage', models.IntegerField(default=50)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_confidence_votes', to=settings.AUTH_USER_MODEL)),
                ('target_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_votes_against', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_votes', to='parties.party')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfidenceBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('CONFIDENCE', 'Confidence'), ('NO_CONFIDENCE', 'No Confidence')], max_length=20)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_ballots', to=settings.AUTH_USER_MODEL)),
                ('confidence_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='parties.confidencevote')),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('confidence_vote', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='LeadershipVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parties.leadershipcandidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parties.leadershipelection')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('election', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Why do you want to join this party?')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_join_requests', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='parties.party')),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('user', 'party')},
            },
        ),
        migrations.CreateModel(
            name='PartyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_founding_member', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='parties.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'party')},
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'Party Leader'), ('DEPUTY', 'Deputy Leader'), ('PRESS', 'Press Secretary'), ('WHIP', 'Party Whip'), ('TREASURER', 'Treasurer'), ('EXECUTIVE', 'Executive Member'), ('ORGANIZER', 'Organizer')], max_length=20)),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_roles', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='parties.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointed_at'],
                'unique_together': {('party', 'user', 'role')},
            },
        ),
    ]
