# Generated by Django 6.0 on 2025-12-19 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_flair_thread_flair'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.politicalparty')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_history', to='forum.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Party Histories',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('MP', 'Member of Parliament'), ('SENATOR', 'Senator'), ('PM', 'Prime Minister'), ('DEPUTY_PM', 'Deputy Prime Minister'), ('MINISTER', 'Cabinet Minister'), ('PARL_SEC', 'Parliamentary Secretary'), ('LEADER', 'Party Leader'), ('DEPUTY_LEADER', 'Deputy Party Leader'), ('HOUSE_LEADER', 'House Leader'), ('WHIP', 'Party Whip'), ('CRITIC', 'Opposition Critic'), ('SPEAKER', 'Speaker of the House'), ('DEPUTY_SPEAKER', 'Deputy Speaker'), ('COMMITTEE_CHAIR', 'Committee Chair'), ('COMMITTEE_MEMBER', 'Committee Member')], max_length=50)),
                ('position_title', models.CharField(max_length=200)),
                ('riding', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='forum.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Position Histories',
                'ordering': ['-start_date'],
            },
        ),
    ]
