# Generated by Django 6.0 on 2025-12-19 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_partyhistory_positionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=2)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['province', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='riding_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='riding_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_holders', to='forum.riding'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='riding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='forum.riding'),
        ),
    ]
