# Generated by Django 6.0 on 2025-12-19 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_riding_userprofile_riding_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('government_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinets', to='forum.politicalparty')),
                ('prime_minister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinets_led', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CabinetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('PM', 'Prime Minister'), ('DEPUTY_PM', 'Deputy Prime Minister'), ('MINISTER', 'Minister'), ('MINISTER_STATE', 'Minister of State'), ('PARL_SEC', 'Parliamentary Secretary')], max_length=50)),
                ('portfolio', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='forum.cabinet')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_positions', to='forum.userprofile')),
            ],
            options={
                'ordering': ['cabinet', 'order', 'portfolio'],
            },
        ),
    ]
