# Generated by Django 6.0 on 2025-12-22 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0005_cabinet_cabinetposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('election_type', models.CharField(choices=[('FEDERAL', 'Federal Election'), ('BY_ELECTION', 'By-Election')], max_length=20)),
                ('election_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_seats', models.IntegerField(default=0)),
                ('total_votes_cast', models.IntegerField(default=0)),
                ('total_registered_voters', models.IntegerField(blank=True, null=True)),
                ('voter_turnout', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('riding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='byelections', to='forum.riding')),
            ],
            options={
                'ordering': ['-election_date'],
            },
        ),
        migrations.CreateModel(
            name='RidingElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes_cast', models.IntegerField(default=0)),
                ('total_registered_voters', models.IntegerField(blank=True, null=True)),
                ('turnout_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_acclaimed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riding_results', to='elections.election')),
                ('previous_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_ridings', to='forum.politicalparty')),
                ('previous_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_elections', to='forum.userprofile')),
                ('riding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_results', to='forum.riding')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_won', to='forum.userprofile')),
                ('winning_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ridings_won', to='forum.politicalparty')),
            ],
            options={
                'ordering': ['riding__province', 'riding__name'],
                'unique_together': {('election', 'riding')},
            },
        ),
        migrations.CreateModel(
            name='CandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('vote_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('is_incumbent', models.BooleanField(default=False)),
                ('votes_previous', models.IntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_candidacies', to='forum.userprofile')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.politicalparty')),
                ('riding_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_results', to='elections.ridingelectionresult')),
            ],
            options={
                'ordering': ['-votes'],
                'unique_together': {('riding_result', 'candidate')},
            },
        ),
    ]
