# Generated by Django 6.0 on 2026-02-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridingelectionresult',
            options={'ordering': ['riding__name']},
        ),
    ]
