# Generated by Django 6.0 on 2025-12-18 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('short_title', models.CharField(blank=True, max_length=150)),
                ('chamber', models.CharField(choices=[('COMMONS', 'House of Commons'), ('SENATE', 'Senate')], default='COMMONS', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FIRST_READING', 'First Reading'), ('SECOND_READING', 'Second Reading'), ('COMMITTEE', 'In Committee'), ('THIRD_READING', 'Third Reading'), ('ROYAL_ASSENT', 'Royal Assent'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('summary', models.TextField()),
                ('full_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('yea_votes', models.IntegerField(default=0)),
                ('nay_votes', models.IntegerField(default=0)),
                ('abstain_votes', models.IntegerField(default=0)),
                ('bills_sponsored', models.IntegerField(default=0)),
                ('bills_passed', models.IntegerField(default=0)),
                ('bills_failed', models.IntegerField(default=0)),
                ('threads_created', models.IntegerField(default=0)),
                ('posts_made', models.IntegerField(default=0)),
                ('participation_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('FIRST', 'First Reading Vote'), ('SECOND', 'Second Reading Vote'), ('THIRD', 'Third Reading Vote'), ('AMENDMENT', 'Amendment Vote'), ('COMMITTEE', 'Committee Vote')], max_length=20)),
                ('description', models.TextField()),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closes_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.bill')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('YEA', 'Yea'), ('NAY', 'Nay'), ('ABSTAIN', 'Abstain')], max_length=10)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.vote')),
            ],
            options={
                'ordering': ['-cast_at'],
                'unique_together': {('vote_session', 'voter')},
            },
        ),
    ]
