# Generated by Django 6.0 on 2025-12-22 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0005_cabinet_cabinetposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('content', models.TextField(help_text='Full press release content with HTML formatting')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary (auto-generated if blank)', max_length=500)),
                ('featured_image', models.TextField(blank=True, help_text='Base64 encoded image data')),
                ('featured_image_caption', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('STATEMENT', 'Statement'), ('POLICY', 'Policy Release'), ('EVENT', 'Event Coverage'), ('RESPONSE', 'Response'), ('OPINION', 'Opinion/Editorial'), ('OTHER', 'Other')], default='ANNOUNCEMENT', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_releases', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_releases', to='forum.politicalparty')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(help_text='Base64 encoded image data')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('press_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='press.pressrelease')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PressComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('press_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='press.pressrelease')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pressrelease',
            index=models.Index(fields=['-published_at'], name='press_press_publish_ce2218_idx'),
        ),
        migrations.AddIndex(
            model_name='pressrelease',
            index=models.Index(fields=['is_published', '-published_at'], name='press_press_is_publ_9d03fa_idx'),
        ),
    ]
