# Generated by Django 6.0 on 2025-12-20 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CABINET_APPOINTED', 'Cabinet Appointment'), ('CABINET_REMOVED', 'Cabinet Removal'), ('VOTE_OPENED', 'Vote Opened'), ('VOTE_CLOSING', 'Vote Closing Soon'), ('VOTE_CLOSED', 'Vote Closed'), ('BILL_CREATED', 'New Bill'), ('BILL_STATUS', 'Bill Status Changed'), ('THREAD_REPLY', 'Thread Reply'), ('MENTION', 'Mentioned'), ('POSITION_CHANGED', 'Position Changed'), ('PARTY_CHANGED', 'Party Changed'), ('GENERAL', 'General Notification')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_bill_id', models.IntegerField(blank=True, null=True)),
                ('related_vote_id', models.IntegerField(blank=True, null=True)),
                ('related_thread_id', models.IntegerField(blank=True, null=True)),
                ('related_user_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_cabinet_change', models.BooleanField(default=True)),
                ('email_on_vote_opened', models.BooleanField(default=True)),
                ('email_on_vote_closing', models.BooleanField(default=True)),
                ('email_on_thread_reply', models.BooleanField(default=True)),
                ('email_on_mention', models.BooleanField(default=True)),
                ('notify_cabinet_change', models.BooleanField(default=True)),
                ('notify_vote_opened', models.BooleanField(default=True)),
                ('notify_vote_closing', models.BooleanField(default=True)),
                ('notify_bill_updates', models.BooleanField(default=True)),
                ('notify_thread_reply', models.BooleanField(default=True)),
                ('notify_mention', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
